public class addsubmulti {
   
     
    public static integer SumOfAddition (integer NumA , integer NumB) {
         integer sum;
       sum = NumA + NumB ;
        return sum;
        
    }
       
    public static integer SumOfSub (integer NumA , integer NumB){
                  integer sub;
         sub = NumA - NumB ;
        return sub;
    }

         
    public static integer SumOfMulti (integer NumA , integer NumB) {
        
         integer Multi;
         Multi = NumA * NumB ;
         return Multi;
        
    }
}