public class sumandmulApexClass {
    
    integer VarAddition;
    integer VarMultiplication;
    
    public integer MakingAddition(integer VarNumber1, integer VarNumber2)
    {
        VarAddition = VarNumber1 + VarNumber2;
        
        return VarAddition;
    }
    
    public integer MakingMultiplication(integer VarNumber1,integer VarNumber2)
    {
        VarMultiplication = VarNumber1 * VarNumber2;

        return VarMultiplication;
    }
}